name: Continue on error test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: "failed step"
        continue-on-error: true
        run: exit 1
      - name: "continue step without if"
        run: echo "hello world"
      - name: "test no continue with success"
        if: success()
        run: echo "hello world 2"
      - name: "test no continue with failure"
        if: failure()
        run: echo "hello world 3"
        
      
